---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-testing
  namespace: todo
  labels:
    app: performance-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: performance-testing
  template:
    metadata:
      labels:
        app: performance-testing
    spec:
      containers:
      - name: performance-testing
        image: adesso/performance-testing:todo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: performance-testing
  namespace: todo
spec:
  selector:
    app: performance-testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: todo
  type: NodePort
